AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: LinkHub - Milestone 1 (Lambda + DynamoDB + HTTP API)

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 10
    MemorySize: 256
    Environment:
      Variables:
        LINKS_TABLE: !Ref LinksTable

Resources:
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowHeaders:
          - "content-type"
        AllowMethods:
          - GET
          - POST

  LinksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: linkhub-links
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: code
          AttributeType: S
      KeySchema:
        - AttributeName: code
          KeyType: HASH

  CreateLinkFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: nodejs20.x
    Properties:
      CodeUri: dist
      Handler: functions/createLink/handler.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LinksTable
      Events:
        CreateLink:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /links
            Method: POST

  RedirectFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: nodejs20.x
    Properties:
      CodeUri: dist
      Handler: functions/redirect/handler.handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref LinksTable
      Events:
        Redirect:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /{code}
            Method: GET

Outputs:
  ApiBaseUrl:
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com"
  LinksTableName:
    Value: !Ref LinksTable